import * as mongoose from 'mongoose';

export const BusinessSchema = new mongoose.Schema({
    id: {type: String},
    originalItem: {
        id: Number,
        creator_user_id: Number,
        user_id: Number,
        person_id: Number,
        org_id: String,
        stage_id: Number,
        title: String,
        value: Number,
        currency: String,
        add_time: String,
        update_time: String,
        stage_change_time: String,
        active: Boolean,
        deleted: Boolean,
        status: String,
        probability: String,
        next_activity_date: String,
        next_activity_time: String,
        next_activity_id: String,
        last_activity_id: String,
        last_activity_date: String,
        lost_reason: String,
        visible_to: String,
        close_time: String,
        pipeline_id: Number,
        won_time: String,
        first_won_time: String,
        lost_time: String,
        products_count: Number,
        files_count: Number,
        notes_count: Number,
        followers_count: Number,
        email_messages_count: Number,
        activities_count: Number,
        done_activities_count: Number,
        undone_activities_count: Number,
        participants_count: Number,
        expected_close_date: String,
        last_incoming_mail_time: String,
        last_outgoing_mail_time: String,
        label: String,
        renewal_type: String,
        stage_order_nr: Number,
        person_name: String,
        org_name: String,
        next_activity_subject: String,
        next_activity_type: String,
        next_activity_duration: String,
        next_activity_note: String,
        group_id: String,
        group_name: String,
        formatted_value: String,
        weighted_value: Number,
        formatted_weighted_value: String,
        weighted_value_currency: String,
        rotten_time: String,
        owner_name: String,
        cc_email: String,
        org_hidden: Boolean,
        person_hidden: Boolean
    },
    parsedItem: {}
}, {collection: 'business', timestamps: true});
